name: build-projects
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: make install
    - run: make test
    - run: make lint
